# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ mk-node-ci ]
  pull_request:
    branches: [ mk-node-ci ]
jobs:
  build:
    name: Build Styleguide 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v2.0.0 
        with: 
          cmd: install 
        env: 
          NODE_ENV: development
      - uses: borales/actions-yarn@v2.0.0 
        with: 
          cmd: yarn build 
